CodeSystem: DataTypes
Id: data-types
Title: "Data Types"
Description: "Data Types Used in INCLUDE Datasets"
* ^url = $data_types
* ^version = "0.1.0"
* ^status = #active
* ^experimental = false
* ^publisher = "NCPI FHIR Works"
* ^content = #fragment
* #Preprocessed-metabolite-relative-abundance "Preprocessed metabolite relative abundance"
* #Protein-abundance-absolute-protein-concentration	"Protein abundance (absolute protein concentration)"
* #Aligned-Reads "Aligned Reads"
* #Aligned-Reads-Index "Aligned Reads Index"
* #Unaligned-Reads "Unaligned Reads"
* #gVCF "gVCF"
* #gVCF-Index "gVCF Index"
* #Peddy-Family-Sex "Peddy - Family/Sex"
* #Variant-Calls "Variant Calls"
* #Variant-Calls-Index "Variant Calls Index"
* #Simple-Nucleotide-Variations "Simple Nucleotide Variations"
* #Somatic-Copy-Number-Variations "Somatic Copy Number Variations"
* #Somatic-Structural-Variations "Somatic Structural Variations"
* #Gene-Fusions "Gene Fusions"
* #Gene-Expression-Quantifications "Gene Expression Quantifications"
* #Raw-Gene-Fusions "Raw Gene Fusions"
* #Isoform-Expression-Quantifications "Isoform Expression Quantifications"
* #Alternative-Splicing "Alternative Splicing"
* #Annotated-Gene-Fusion "Annotated Gene Fusion"
* #Other "Other"
* #Adapter-Stats "Adapter Stats"
* #Alignment-Metrics "Alignment Metrics"
* #Alignment-Stats "Alignment Stats"
* #Alignment-Summary "Alignment Summary"
* #Annotated-Germline-Copy-Number-Segments "Annotated Germline Copy Number Segments"
* #Annotated-Germline-Structural-Variation "Annotated Germline Structural Variation"
* #Annotated-Somatic-Copy-Number-Segment "Annotated Somatic Copy Number Segment"
* #Annotated-Somatic-Mutation "Annotated Somatic Mutation"
* #Annotated-Somatic-Mutation-Index "Annotated Somatic Mutation Index"
* #Annotated-Tumor-Only-Mutation "Annotated Tumor Only Mutation"
* #Annotated-Tumor-Only-Mutation-Index "Annotated Tumor Only Mutation Index"
* #Annotated-Variant-Call "Annotated Variant Call"
* #Annotated-Variant-Call-Index "Annotated Variant Call Index"
* #Artifact-Metrics "Artifact Metrics"
* #Chimeric-Aligned-Reads "Chimeric Aligned Reads"
* #Consensus-Somatic-Mutation "Consensus Somatic Mutation"
* #Consensus-Somatic-Mutation-Index "Consensus Somatic Mutation Index"
* #Contamination-Estimation "Contamination Estimation"
* #Control-Copy-Number "Control Copy Number"
* #Control-Copy-Number-Segment "Control Copy Number Segment"
* #Cutadapter-Metrics "Cutadapter Metrics"
* #Denoised-Germline-Copy-Ratios "Denoised Germline Copy Ratios"
* #Extra-Chromosomal-DNA "Extra-Chromosomal DNA"
* #Familial-Relationship "Familial Relationship"
* #Familial-Relationship-Report "Familial Relationship Report"
* #Familial-Relationships "Familial Relationships"
* #Familial-Relationships-Report "Familial Relationships Report"
* #GC-Metrics "GC Metrics"
* #Gender-Metrics "Gender Metrics"
* #Gender-QC-Metric "Gender QC Metric"
* #Gender-QC-Metrics "Gender QC Metrics"
* #Gene-Expression-Count "Gene Expression Count"
* #Gene-Expression-Quantification "Gene Expression Quantification"
* #Gene-Level-Copy-Number "Gene Level Copy Number"
* #Genome-Aligned-Reads "Genome Aligned Reads"
* #Genome-Aligned-Reads-Index "Genome Aligned Reads Index"
* #Genomic-Variant "Genomic Variant"
* #Genomic-Variant-Index "Genomic Variant Index"
* #Genotyped-Germline-Copy-Number-Intervals "Genotyped Germline Copy Number Intervals"
* #Genotyped-Germline-Copy-Number-Intervals-Index "Genotyped Germline Copy Number Intervals Index"
* #Genotyped-Germline-Copy-Number-Segments "Genotyped Germline Copy Number Segments"
* #Genotyped-Germline-Copy-Number-Segments-Index "Genotyped Germline Copy Number Segments Index"
* #Germline-Copy-Number-Read-Depth-Stats "Germline Copy Number Read Depth Stats"
* #Het-Call-QC-Metric "Het Call QC Metric"
* #Het-Call-QC-Metrics "Het Call QC Metrics"
* #HLA-Genotyping "HLA Genotyping"
* #Insert-Size-Metrics "Insert Size Metrics"
* #Isoform-Expression-Quantification "Isoform Expression Quantification"
* #Masked-Consensus-Somatic-Mutation "Masked Consensus Somatic Mutation"
* #Masked-Consensus-Somatic-Mutation-Index "Masked Consensus Somatic Mutation Index"
* #Masked-Somatic-Mutation "Masked Somatic Mutation"
* #Masked-Somatic-Mutation-Index "Masked Somatic Mutation Index"
* #Masked-Tumor-Only-Mutation "Masked Tumor Only Mutation"
* #Masked-Tumor-Only-Mutation-Index "Masked Tumor Only Mutation Index"
* #Pre-pass-Somatic-Structural-Variation "Pre-pass Somatic Structural Variation"
* #Pre-pass-Somatic-Structural-Variation-Index "Pre-pass Somatic Structural Variation Index"
* #Pre-pass-Tumor-Only-Structural-Variation "Pre-pass Tumor Only Structural Variation"
* #Pre-pass-Tumor-Only-Structural-Variation-Index "Pre-pass Tumor Only Structural Variation Index"
* #QC-Metrics "QC Metrics"
* #Quality-Score-Distribution "Quality Score Distribution"
* #Raw-Gene-Fusion "Raw Gene Fusion"
* #Raw-Germline-Copy-Number-Segments "Raw Germline Copy Number Segments"
* #Raw-Germline-Structural-Variation "Raw Germline Structural Variation"
* #Raw-Germline-Structural-Variation-Index "Raw Germline Structural Variation Index"
* #Raw-Simple-Somatic-Mutation "Raw Simple Somatic Mutation"
* #Raw-Simple-Somatic-Mutation-Index "Raw Simple Somatic Mutation Index"
* #Raw-Somatic-Copy-Number-Segment "Raw Somatic Copy Number Segment"
* #Raw-Somatic-Structural-Variation "Raw Somatic Structural Variation"
* #Raw-Somatic-Structural-Variation-Index "Raw Somatic Structural Variation Index"
* #Raw-Tumor-Only-Copy-Number-Segment "Raw Tumor Only Copy Number Segment"
* #Raw-Tumor-Only-Structural-Variation "Raw Tumor Only Structural Variation"
* #Raw-Tumor-Only-Structural-Variation-Index "Raw Tumor Only Structural Variation Index"
* #Raw-Variant-Call "Raw Variant Call"
* #Raw-Variant-Call-Index "Raw Variant Call Index"
* #Recalibration-Report "Recalibration Report"
* #Reference-Copy-Number-Profiling "Reference Copy Number Profiling"
* #Relatedness-QC-Metric "Relatedness QC Metric"
* #Relatedness-QC-Metrics "Relatedness QC Metrics"
* #RNAseq-Alignment-Metrics "RNAseq Alignment Metrics"
* #Somatic-Copy-Number "Somatic Copy Number"
* #Somatic-Copy-Number-BAF "Somatic Copy Number BAF"
* #Somatic-Copy-Number-Diagram "Somatic Copy Number Diagram"
* #Somatic-Copy-Number-Metrics "Somatic Copy Number Metrics"
* #Somatic-Copy-Number-Ratio "Somatic Copy Number Ratio"
* #Somatic-Copy-Number-Scatter "Somatic Copy Number Scatter"
* #Somatic-Copy-Number-Segment "Somatic Copy Number Segment"
* #Somatic-Copy-Number-Subclone-Segment "Somatic Copy Number Subclone Segment"
* #Somatic-Copy-Number-Variation "Somatic Copy Number Variation"
* #Somatic-Structural-Variation "Somatic Structural Variation"
* #Splice-Junction "Splice Junction"
* #Tool-Log "Tool Log"
* #Tumor-Copy-Number "Tumor Copy Number"
* #Tumor-Copy-Number-Segment "Tumor Copy Number Segment"
* #Tumor-Only-Assembled-Haplotypes "Tumor Only Assembled Haplotypes"
* #Tumor-Only-Assembled-Haplotypes-Index "Tumor Only Assembled Haplotypes Index"
* #Tumor-Only-Copy-Number-BAF "Tumor Only Copy Number BAF"
* #Tumor-Only-Copy-Number-Ratio "Tumor Only Copy Number Ratio"
* #Tumor-Only-Copy-Number-Variation "Tumor Only Copy Number Variation"
* #Tumor-Only-Structural-Variation "Tumor Only Structural Variation"
* #Tumor-Ploidy-and-Purity "Tumor Ploidy and Purity"
* #Tumor-Purity "Tumor Purity"
* #Variant-Calling-Metrics "Variant Calling Metrics"
* #WGS-Metrics "WGS Metrics"
* #WXS-Metrics "WXS Metrics"
